version: "3.8"
services:
  frontend:
    build: 
      context: ./react-app
      dockerfile: Dockerfile
    env_file: ./react-app/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    hostname: frontend
    networks:
      - alaga-network
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/react-app
      - /react-app/node_modules
    stdin_open: true

  backend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file: .env
    hostname: backend
    networks:
      - alaga-network
    ports:
      - "5000:5000"
      - "5432:5432"
    volumes:
      - ./app:/app
      - ./migrations:/migrations
    command: gunicorn app:app -c ./app/gunicorn.conf.py
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  alaga-network:
    name: alaga-network
    driver: bridge

      
