version: "3.8"
services:
  db:
    image: postgres:12
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./init-pg.sh:/docker-entrypoint-initdb.d/init-pg.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"